-- AlterTable
ALTER TABLE "Ingredient" ADD COLUMN     "barcode" TEXT,
ADD COLUMN     "carbs" DOUBLE PRECISION,
ADD COLUMN     "fat" DOUBLE PRECISION,
ADD COLUMN     "fiber" DOUBLE PRECISION,
ADD COLUMN     "kcal" DOUBLE PRECISION,
ADD COLUMN     "protein" DOUBLE PRECISION,
ADD COLUMN     "sugar" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Meal" ADD COLUMN     "macrosManual" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves" DOUBLE PRECISION NOT NULL DEFAULT 1;
